### ISSUE TITLE
Autosuggest - cant filter the results as `post_filter` is hardcoded. 

### ISSUE THREAD

**Issue by mattheu** [humanmade/altis-enhanced-search#308]
My use case: I want to prevent posts with the meta key 'unlisted' from being displayed in autosuggest results. 

I have tried filtering the query used to pass either a `meta_query`, or `post__not_in`, but neither approach works. In Chrome dev tools I can see the correct es query options being passed as part of the request to `/autosuggest`, but these seem to be having no effect. 

Further investigation it is because this is using the`post_filter` argument, and this is completely overridden here: https://github.com/humanmade/altis-enhanced-search/blob/master/inc/namespace.php#L1981

IMO this is a bug, as I would expect this to work. It is also pretty opaque that this argument is hardcoded and took me a couple of hours to work out why this didn't work. 

Not opening a PR as I don't really have a deep knowledge of this functionality, but perhaps this would be a better solution: 

```php
	// Force post filter value.
	$json = array_merge_recursive( $json, [
		'post_filter' => [
			'bool' => [
				'must' => [
					[
						'term' => [
							'post_status' => 'publish',
						],
					],
					[
						'terms' => [
							'post_type.raw' => array_values( $search->get_searchable_post_types() ),
						],
					],
				],
			],
			],
	] );
```

**Comment by roborourke** [comment]
Noting here too that this is hardcoded because the request from the client side is the actual Elasticsearch query JSON intended to be forwarded straight to ES.

The `post_filter` is therefore hardcoded server side to prevent potentially leaking any unpublished or non searchable content. So it is indeed intentional.

That said devs should be allowed to modify the query server side too. The PR #309 should allow for this.
