### ISSUE TITLE
SPIKE: Investigate options for ElaticPress proxy endpoint

### ISSUE THREAD

**Issue by veselala** [humanmade/altis-enhanced-search#428]
#410 

Timebox: 1 day

**Comment by veselala** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-enhanced-search/428?planning-poker) with ZenHub @ferschubert-hm @jerico @kovshenin @mikelittle @wisyhambolu

**Comment by kovshenin** [comment]
Potential solutions discussed today during refinement:

* Write .php/.json credentials/settings to /tmp in each instance on demand (when proxy is first accessed), which means loading the WP instance in some cases when the proxy is loaded
* Write/read the credentials from Redis, possibly cache on disk in each container for some time to prevent querying Redis too much
* Share credentials with all containers using an EFS/NFS mount (not ideal performance)

Things to consider:

* Autoscaling events can create new containers with empty /tmp directories
* Redis can evict these credentials if they're not used often
* Users can trigger a reindexing event which should properly invalidate caches in all containers

If you have any other ideas or considerations please drop them here!

**Comment by rmccue** [comment]
I'm not sure I understand why we'd need to write a file at all here; our write-xor-execute filesystem (via it being read-only) is a strong security feature that we shouldn't break. It looks like EP is doing this as a bit of a hack to cache information on the filesystem that can be read by the standalone script, but there's no reason we need to do the same, and in fact we'd need to override the behaviour they have anyway since it's [hardcoded to uploads](https://github.com/10up/elasticpress-proxy/blob/5dc91bee613275f6089b192a792282c309b83f8a/proxy.php#L81).

The actual problem that needs solving here is being able to query Elasticsearch from the frontend while keeping the querying performant.

10up is solving this in their script by doing that with a standalone script and this weird credentials file, but it's not clear to me if that's really necessary to solve this problem, and I'd question any standalone entrypoint in any plugin. (This is the sort of thing that sounds alarms from the security part of my brain.)

Is the standalone entrypoint _truly_ necessary for performance? What are the _actual_ performance gains in practice, compared to something like triggering on `plugins_loaded`? (In my experience, the thing that's slow is the Elasticsearch query, not bootstrapping WordPress.) Do those gains outweigh the problems inherent in this approach?

Naively, my approach would be to take the functionality [in ep-proxy](https://github.com/10up/elasticpress-proxy/blob/develop/proxy.php), strip the standalone-script-weirdness bits, and see how that goes.

**Comment by kovshenin** [comment]
Hmm, I think you're right. I feel like the problem 10up was trying to address with the proxy is when bootstrapping WordPress does take a significant amount of time. Maybe we could do a `SHORTINIT` and close the database connections *before* firing the request off to Elasticsearch if we believe that may take a while?

**Comment by rmccue** [comment]
Maybe, but we should test the assumption that WordPress bootstrap is slow! (This is basically the same argument we used to have way back in the day with the REST API, and that's been plenty performant for most people.)

I'm not sure that `SHORTINIT` or a separate script is going to have a perceptible user impact.

**Comment by veselala** [comment]
On the Vulcan's planning session 08/08/22 was discussed to not have this spike (also as per @rmccue's comment) and will proceed directly with the refinement of #410
